flashcard/urls.py
from django.urls import path

from . import views

app_name = "flashcard"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:fcs_id>/", views.fcs_detail, name="fcs_detail"),
    path("fc/<int:fc_id>/", views.FlashcardDetailView.as_view(), name="fc_detail"),
]

polls/urls.py
from django.urls import path

from polls import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

remembering/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("flashcard/", include("flashcard.urls")),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

flashcard/models.py
from django.db import models
from datetime import timedelta
from django.contrib.auth.models import User

from django.utils import timezone


class FlashcardSet(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title


class Flashcard(models.Model):
    question = models.TextField(max_length=200)
    answer = models.TextField(default="", max_length=5000)
    flashcard_set = models.ForeignKey(FlashcardSet, on_delete=models.CASCADE)
    last_reviewed = models.DateField(null=True)
    next_review = models.DateField(null=True)
    ease_factor = models.FloatField(default=2.5)
    repetition = models.IntegerField(default=0)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.question

    def update_review(self, success: bool, quality: int) -> None:
        if success:
            self.repetition += 1
        else:
            self.repetition = 0

        self.ease_factor = max(1.3, self.ease_factor + 0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02))

        self.last_reviewed = timezone.now()
        self.next_review = self.last_reviewed + timedelta(days=self.repetition * self.ease_factor)


class Review(models.Model):
    flashcard = models.ForeignKey(Flashcard, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    success = models.BooleanField()
    quality = models.IntegerField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'Review for flashcard: {self.flashcard.question}'


class ReviewSession(models.Model):
    flashcard_set = models.ForeignKey(FlashcardSet, on_delete=models.CASCADE)
    reviews = models.ManyToManyField(Review)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'Review session for flashcard set: {self.flashcard_set.title}'

polls/models.py
import datetime

from django.db import models
from django.contrib import admin
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

flashcard/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import QuerySet
from django.shortcuts import get_object_or_404, render
from django.views import generic

from flashcard.models import FlashcardSet, Flashcard


def index(request: WSGIRequest):
    your_fcs_list: QuerySet[FlashcardSet]

    if request.user.is_anonymous:
        your_fcs_list = QuerySet[FlashcardSet]()
    else:
        your_fcs_list = FlashcardSet.objects.filter(created_by=request.user)

    return render(
        request,
        "flashcard/fcs_list.html",
        {
            "your_fcs_list": your_fcs_list,
        },
    )


def fcs_detail(request: WSGIRequest, fcs_id: int):
    fcs: FlashcardSet = get_object_or_404(FlashcardSet, pk=fcs_id)
    list_fc: QuerySet[Flashcard] = Flashcard.objects.filter(flashcard_set=fcs)

    return render(
        request,
        "flashcard/fcs_detail.html",
        {
            "fcs": fcs,
            "list_fc": list_fc,
        },
    )


class FlashcardDetailView(generic.DetailView):
    model = Flashcard
    template_name = "flashcard/fc_detail.html"
    context_object_name = "flashcard"
    pk_url_kwarg = "fc_id"

    def get_queryset(self):
        return Flashcard.objects.filter(created_by=self.request.user)

polls/views.py
from django.db.models import F
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from polls.models import Question, Choice


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

flashcard/templates/flashcard/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>To-Do List</title>

    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.0.9/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com?plugins=typography"></script>
    <script src="https://unpkg.com/htmx.org@1.9.8" integrity="sha384-rgjA7mptc2ETQqXoYC3/zJvkU7K/aP44Y+z7xQuJiVnB/422P/Ak+F/AqFR7E4Wr" crossorigin="anonymous"></script>

</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

    <div class="mt-4 ml-4">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

flashcard/templates/flashcard/fc_detail.html
{% extends 'flashcard/base.html' %}

{% block content %}
    <h1 class="text-xl">Flashcard</h1>

    <div class="card w-70 bg-base-100 shadow-xl">
        <div class="card-body">
            <h2 class="card-title">{{ flashcard.question }}</h2>
            <p>{{ flashcard.answer }}</p>
        </div>
    </div>

{% endblock %}

flashcard/templates/flashcard/fcs_detail.html
{% extends 'flashcard/base.html' %}

{% block content %}
    <h1>{{ fcs.title }}</h1>
    <p>{{ fcs.description }}</p>
    <p>Published: {{ fcs.created_at|date }}</p>
    <p>Updated: {{ fcs.updated_at|date }}</p>

    <br/>
    <h1 class="text-xl">List flashcards</h1>

    {% if list_fc %}
        <div class="grid grid-cols-4 gap-4">
            {% for fc in list_fc %}
                <div class="card w-70 bg-base-100 shadow-xl">
                    <div class="card-body">
                        <h2 class="card-title">{{ fc.question }}</h2>
                        <p>{{ fc.answer }}</p>
                        <div class="card-actions justify-end">
                            <a class="btn btn-primary" href="{% url "flashcard:fc_detail" fc.id %}">Edit</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No flashcard are available.</p>
    {% endif %}
{% endblock %}

flashcard/templates/flashcard/fcs_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>

flashcard/templates/flashcard/fcs_list.html
{% extends 'flashcard/base.html' %}

{% block content %}
    <div class="lg:container">
        <h2 class="text-3xl">Your flash card set</h2>

        {% if your_fcs_list %}
            <div class="grid grid-cols-4 gap-4">
                {% for fcs in your_fcs_list %}
                    <div class="card w-70 bg-base-100 shadow-xl">
                        <div class="card-body">
                            <h2 class="card-title">{{ fcs.title }}</h2>
                            <p>{{ fcs.description }}</p>
                            <div class="card-actions justify-end">
                                <a class="btn btn-primary" href="{% url "flashcard:fcs_detail" fcs.id %}">Learn now</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No flashcard set are available.</p>
        {% endif %}
    </div>

{% endblock %}

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>